CREATE TABLE KH_STUDENT (
	STD_NO NUMBER PRIMARY KEY,
	STD_NAME NVARCHAR2(5) NOT NULL,
	STD_AGE NUMBER NOT NULL,
	MAJOR NVARCHAR2(10) NOT NULL,
	ENT_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM KH_STUDENT;

CREATE SEQUENCE SEQ_STD_NO
START WITH 101
INCREMENT BY 1;

SELECT STD_NO
FROM KH_STUDENT
WHERE STD_NO = 101;
